[svn] configure: redesign for [-_]config; added for MAGICK

diff --git a/trunk/configure b/trunk/configure
--- a/trunk/configure
+++ b/trunk/configure
@@ -1282,6 +1282,8 @@ Optional Packages:
   --with-bzip2(=/path)    use bzip2
   --with-zlib(=/path)     use zlib
   --with-iconv(=/path)    use iconv
+  --with-imagemagick(=/path)
+                          use ImageMagick
 
 Some influential environment variables:
   CXX         C++ compiler command
@@ -3752,7 +3754,6 @@ echo "" > include/libdodo/directives.runtime.h
 
 CPPFLAGS="$CPPFLAGS -I/usr/local/include"
 LDFLAGS="$LDFLAGS -L/usr/local/lib"
-LIBS=""
 
 RESULT="\n\n"
 
@@ -3822,7 +3823,7 @@ fi
 			MOD_SQLITE_DIR=/usr
 		fi
 		CPPFLAGS="$CPPFLAGS -I$MOD_SQLITE_DIR/include"
-		LDFLAGS="$LDFLAGS -L$MOD_SQLITE_DIR/lib"
+		LDFLAGS="$LDFLAGS -L$MOD_SQLITE_DIR/lib -lsqlite3"
 		{ echo "$as_me:$LINENO: checking for sqlite3_table_column_metadata in -lsqlite3" >&5
 echo $ECHO_N "checking for sqlite3_table_column_metadata in -lsqlite3... $ECHO_C" >&6; }
 if test "${ac_cv_lib_sqlite3_sqlite3_table_column_metadata+set}" = set; then
@@ -4499,7 +4500,6 @@ echo "${ECHO_T}$ac_cv_header_sqlite3_h" >&6; }
 fi
 
 
-		LIBS="$LIBS -lsqlite3"
 		echo -n -e "#define SQLITE_EXT\n\n" >> include/libdodo/directives.runtime.h
 
 		RESULT="$RESULT\nSQLite\t\t\t\t\t\tenabled"
@@ -4522,7 +4522,7 @@ fi
 			MOD_POSTGRESQL_DIR=/usr
 		fi
 		CPPFLAGS="$CPPFLAGS -I$MOD_POSTGRESQL_DIR/include"
-		LDFLAGS="$LDFLAGS -L$MOD_POSTGRESQL_DIR/lib"
+		LDFLAGS="$LDFLAGS -L$MOD_POSTGRESQL_DIR/lib -lpq"
 
 { echo "$as_me:$LINENO: checking for PQclear in -lpq" >&5
 echo $ECHO_N "checking for PQclear in -lpq... $ECHO_C" >&6; }
@@ -4726,13 +4726,11 @@ echo "${ECHO_T}$ac_cv_header_libpq_fe_h" >&6; }
 fi
 
 
-		LIBS="$LIBS -lpq"
 		echo -n -e "#define POSTGRESQL_EXT\n\n" >> include/libdodo/directives.runtime.h
 
 		RESULT="$RESULT\nPostresql\t\t\t\t\t\tenabled"
 	else
 		RESULT="$RESULT\nPostgresql\t\t\t\t\t\tdisabled"
-
 	fi
 
 
@@ -4747,10 +4745,13 @@ fi
 	then
 		if test "$MOD_MYSQL_DIR" = "yes"
 		then
+			CPPFLAGS="$CPPFLAGS $(mysql_config --cflags)"
+			LDFLAGS="$LDFLAGS $(mysql_config --libs)"
+		else
 			MOD_MYSQL_DIR=/usr
+			CPPFLAGS="$CPPFLAGS -I$MOD_MYSQL_DIR/include"
+			LDFLAGS="$LDFLAGS -L$MOD_MYSQL_DIR/lib -lmysqlclient"
 		fi
-		CPPFLAGS="$CPPFLAGS -I$MOD_MYSQL_DIR/include/mysql"
-		LDFLAGS="$LDFLAGS -L$MOD_MYSQL_DIR/lib/mysql"
 
 { echo "$as_me:$LINENO: checking for mysql_init in -lmysqlclient" >&5
 echo $ECHO_N "checking for mysql_init in -lmysqlclient... $ECHO_C" >&6; }
@@ -4954,14 +4955,11 @@ echo "${ECHO_T}$ac_cv_header_mysql_h" >&6; }
 fi
 
 
-		LIBS="$LIBS -lmysqlclient"
 		echo -n -e "#define MYSQL_EXT\n\n" >> include/libdodo/directives.runtime.h
 
 		RESULT="$RESULT\nMySQL\t\t\t\t\t\tenabled"
 	else
 		RESULT="$RESULT\nMySQL\t\t\t\t\t\tdisabled"
-
-
 	fi
 
 
@@ -4979,7 +4977,7 @@ fi
 			MOD_FCGI_DIR=/usr
 		fi
 		CPPFLAGS="$CPPFLAGS -I$MOD_FCGI_DIR/include"
-		LDFLAGS="$LDFLAGS -L$MOD_FCGI_DIR/lib"
+		LDFLAGS="$LDFLAGS -L$MOD_FCGI_DIR/lib -lfcgi"
 
 { echo "$as_me:$LINENO: checking for FCGX_Init in -lfcgi" >&5
 echo $ECHO_N "checking for FCGX_Init in -lfcgi... $ECHO_C" >&6; }
@@ -5183,12 +5181,11 @@ echo "${ECHO_T}$ac_cv_header_fcgiapp_h" >&6; }
 fi
 
 
-		LIBS="$LIBS -lfcgi"
 		echo -n -e "#define FCGI_EXT\n\n" >> include/libdodo/directives.runtime.h
 
-		RESULT="$RESULT\nPostgresql\t\t\t\t\t\tenabled"
+		RESULT="$RESULT\nFastCGI\t\t\t\t\t\tenabled"
 	else
-		RESULT="$RESULT\nPostgresql\t\t\t\t\t\tdisabled"
+		RESULT="$RESULT\nFastCGI\t\t\t\t\t\tdisabled"
 	fi
 
 
@@ -5203,10 +5200,13 @@ fi
 	then
 		if test "$MOD_PCRE_DIR" = "yes"
 		then
+			CPPFLAGS="$CPPFLAGS $(pcre-config --cflags)"
+			LDFLAGS="$LDFLAGS $(pcre-config --libs)"
+		else
 			MOD_PCRE_DIR=/usr
+			CPPFLAGS="$CPPFLAGS -I$MOD_PCRE_DIR/include"
+			LDFLAGS="$LDFLAGS -L$MOD_PCRE_DIR/lib -lpcre"
 		fi
-		CPPFLAGS="$CPPFLAGS -I$MOD_PCRE_DIR/include"
-		LDFLAGS="$LDFLAGS -L$MOD_PCRE_DIR/lib"
 
 { echo "$as_me:$LINENO: checking for pcre_exec in -lpcre" >&5
 echo $ECHO_N "checking for pcre_exec in -lpcre... $ECHO_C" >&6; }
@@ -5410,7 +5410,6 @@ echo "${ECHO_T}$ac_cv_header_pcre_h" >&6; }
 fi
 
 
-		LIBS="$LIBS -lpcre"
 		echo -n -e "#define PCRE_EXT\n\n" >> include/libdodo/directives.runtime.h
 
 		RESULT="$RESULT\nPCRE\t\t\t\t\t\tenabled"
@@ -5642,7 +5641,7 @@ else
   RESULT="$RESULT\nDynamic linking as lib\t\t\t\t\t\tdisabled"
 fi
 
-			LIBS="$LIBS -ldl"
+			LDFLAGS="$LDFLAGS -ldl"
 		fi
 		echo -n -e "#define DL_EXT\n\n" >> include/libdodo/directives.runtime.h
 
@@ -5663,10 +5662,13 @@ fi
 	then
 		if test "$MOD_LIBXML2_DIR" = "yes"
 		then
+			CPPFLAGS="$CPPFLAGS $(xml2-config --cflags)"
+			LDFLAGS="$LDFLAGS $(xml2-config --libs)"
+		else
 			MOD_LIBXML2_DIR=/usr
+			CPPFLAGS="$CPPFLAGS -I$MOD_LIBXML2_DIR/include/libxml2"
+			LDFLAGS="$LDFLAGS -L$MOD_LIBXML2_DIR/lib -lxml2"
 		fi
-		CPPFLAGS="$CPPFLAGS -I$MOD_LIBXML2_DIR/include/libxml2"
-		LDFLAGS="$LDFLAGS -L$MOD_LIBXML2_DIR/lib"
 		if test "${ac_cv_header_libxml_xmlmemory_h+set}" = set; then
   { echo "$as_me:$LINENO: checking for libxml/xmlmemory.h" >&5
 echo $ECHO_N "checking for libxml/xmlmemory.h... $ECHO_C" >&6; }
@@ -5870,7 +5872,6 @@ _ACEOF
 
 fi
 
-		LIBS="$LIBS -lxml2"
 		echo -n -e "#define LIBXML2_EXT\n\n" >> include/libdodo/directives.runtime.h
 
 		RESULT="$RESULT\nlibxml2\t\t\t\t\t\tenabled"
@@ -5892,8 +5893,6 @@ fi
 		then
 			MOD_PTHREAD_DIR=/usr
 		fi
-		CPPFLAGS="$CPPFLAGS -I$MOD_PTHREAD_DIR/include"
-		LDFLAGS="$LDFLAGS -L$MOD_PTHREAD_DIR/lib"
 
 # Check whether --with-pthread-lib was given.
 if test "${with_pthread_lib+set}" = set; then
@@ -5902,6 +5901,8 @@ else
   MOD_PTHREAD_LIB="pthread"
 fi
 
+		CPPFLAGS="$CPPFLAGS -I$MOD_PTHREAD_DIR/include"
+		LDFLAGS="$LDFLAGS -L$MOD_PTHREAD_DIR/lib -l$MOD_PTHREAD_LIB"
 
 as_ac_Lib=`echo "ac_cv_lib_$MOD_PTHREAD_LIB''_pthread_create" | $as_tr_sh`
 { echo "$as_me:$LINENO: checking for pthread_create in -l$MOD_PTHREAD_LIB" >&5
@@ -6107,7 +6108,6 @@ echo "${ECHO_T}$ac_cv_header_pthread_h" >&6; }
 fi
 
 
-		LIBS="$LIBS -l$MOD_PTHREAD_LIB"
 		echo -n -e "#define PTHREAD_EXT\n\n" >> include/libdodo/directives.runtime.h
 
 		RESULT="$RESULT\npthread\t\t\t\t\t\tenabled($MOD_PTHREAD_LIB)"
@@ -6130,7 +6130,7 @@ fi
 			MOD_BZIP2_DIR=/usr
 		fi
 		CPPFLAGS="$CPPFLAGS -I$MOD_BZIP2_DIR/include"
-		LDFLAGS="$LDFLAGS -L$MOD_BZIP2_DIR/lib"
+		LDFLAGS="$LDFLAGS -L$MOD_BZIP2_DIR/lib -lbz2"
 
 { echo "$as_me:$LINENO: checking for BZ2_bzBuffToBuffCompress in -lbz2" >&5
 echo $ECHO_N "checking for BZ2_bzBuffToBuffCompress in -lbz2... $ECHO_C" >&6; }
@@ -6334,7 +6334,6 @@ echo "${ECHO_T}$ac_cv_header_bzlib_h" >&6; }
 fi
 
 
-		LIBS="$LIBS -lbz2"
 		echo -n -e "#define BZIP2_EXT\n\n" >> include/libdodo/directives.runtime.h
 
 		RESULT="$RESULT\nBZIP2\t\t\t\t\t\tenabled"
@@ -6568,7 +6567,7 @@ _ACEOF
 
 fi
 
-			LIBS="$LIBS -lz"
+			LDFLAGS="$LDFLAGS -lz"
 		fi
 		echo -n -e "#define ZLIB_EXT\n\n" >> include/libdodo/directives.runtime.h
 
@@ -6803,13 +6802,242 @@ _ACEOF
 
 fi
 
-			LIBS="$LIBS -liconv"
+			LDFLAGS="$LDFLAGS -liconv"
 		fi
 		echo -n -e "#define ICONV_EXT\n\n" >> include/libdodo/directives.runtime.h
 
 		RESULT="$RESULT\niconv\t\t\t\t\t\tenabled"
 	else
 		RESULT="$RESULT\niconv\t\t\t\t\t\tdisabled"
+	fi
+
+
+# Check whether --with-imagemagick was given.
+if test "${with_imagemagick+set}" = set; then
+  withval=$with_imagemagick; MOD_IMAGEMAGICK_DIR="$withval"
+else
+  MOD_IMAGEMAGICK="no"
+fi
+
+	if test "$MOD_IMAGEMAGICK" != "no"
+	then
+		if test "$MOD_IMAGEMAGICK_DIR" = "yes"
+		then
+			CPPFLAGS="$CPPFLAGS $(Magick-config --cppflags)"
+			LDFLAGS="$LDFLAGS $(Magick-config --ldflags) $(Magick-config --libs)"
+		else
+			MOD_ICONV_DIR=/usr
+			CPPFLAGS="$CPPFLAGS -I$MOD_IMAGEMAGICK_DIR/include"
+			LDFLAGS="$LDFLAGS -L$MOD_IMAGEMAGICK_DIR/lib -lMagick"
+		fi
+
+{ echo "$as_me:$LINENO: checking for MagickCoreGenesis in -lMagick" >&5
+echo $ECHO_N "checking for MagickCoreGenesis in -lMagick... $ECHO_C" >&6; }
+if test "${ac_cv_lib_Magick_MagickCoreGenesis+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+  ac_check_lib_save_LIBS=$LIBS
+LIBS="-lMagick  $LIBS"
+cat >conftest.$ac_ext <<_ACEOF
+/* confdefs.h.  */
+_ACEOF
+cat confdefs.h >>conftest.$ac_ext
+cat >>conftest.$ac_ext <<_ACEOF
+/* end confdefs.h.  */
+
+/* Override any GCC internal prototype to avoid an error.
+   Use char because int might match the return type of a GCC
+   builtin and then its argument prototype would still apply.  */
+#ifdef __cplusplus
+extern "C"
+#endif
+char MagickCoreGenesis ();
+int
+main ()
+{
+return MagickCoreGenesis ();
+  ;
+  return 0;
+}
+_ACEOF
+rm -f conftest.$ac_objext conftest$ac_exeext
+if { (ac_try="$ac_link"
+case "(($ac_try" in
+  *\"* | *\`* | *\\*) ac_try_echo=\$ac_try;;
+  *) ac_try_echo=$ac_try;;
+esac
+eval "echo \"\$as_me:$LINENO: $ac_try_echo\"") >&5
+  (eval "$ac_link") 2>conftest.er1
+  ac_status=$?
+  grep -v '^ *+' conftest.er1 >conftest.err
+  rm -f conftest.er1
+  cat conftest.err >&5
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } && {
+	 test -z "$ac_c_werror_flag" ||
+	 test ! -s conftest.err
+       } && test -s conftest$ac_exeext &&
+       $as_test_x conftest$ac_exeext; then
+  ac_cv_lib_Magick_MagickCoreGenesis=yes
+else
+  echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
+	ac_cv_lib_Magick_MagickCoreGenesis=no
+fi
+
+rm -f core conftest.err conftest.$ac_objext conftest_ipa8_conftest.oo \
+      conftest$ac_exeext conftest.$ac_ext
+LIBS=$ac_check_lib_save_LIBS
+fi
+{ echo "$as_me:$LINENO: result: $ac_cv_lib_Magick_MagickCoreGenesis" >&5
+echo "${ECHO_T}$ac_cv_lib_Magick_MagickCoreGenesis" >&6; }
+if test $ac_cv_lib_Magick_MagickCoreGenesis = yes; then
+  cat >>confdefs.h <<_ACEOF
+#define HAVE_LIBMAGICK 1
+_ACEOF
+
+  LIBS="-lMagick $LIBS"
+
+fi
+
+		if test "${ac_cv_header_magick_MagickCore_h+set}" = set; then
+  { echo "$as_me:$LINENO: checking for magick/MagickCore.h" >&5
+echo $ECHO_N "checking for magick/MagickCore.h... $ECHO_C" >&6; }
+if test "${ac_cv_header_magick_MagickCore_h+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+fi
+{ echo "$as_me:$LINENO: result: $ac_cv_header_magick_MagickCore_h" >&5
+echo "${ECHO_T}$ac_cv_header_magick_MagickCore_h" >&6; }
+else
+  # Is the header compilable?
+{ echo "$as_me:$LINENO: checking magick/MagickCore.h usability" >&5
+echo $ECHO_N "checking magick/MagickCore.h usability... $ECHO_C" >&6; }
+cat >conftest.$ac_ext <<_ACEOF
+/* confdefs.h.  */
+_ACEOF
+cat confdefs.h >>conftest.$ac_ext
+cat >>conftest.$ac_ext <<_ACEOF
+/* end confdefs.h.  */
+$ac_includes_default
+#include <magick/MagickCore.h>
+_ACEOF
+rm -f conftest.$ac_objext
+if { (ac_try="$ac_compile"
+case "(($ac_try" in
+  *\"* | *\`* | *\\*) ac_try_echo=\$ac_try;;
+  *) ac_try_echo=$ac_try;;
+esac
+eval "echo \"\$as_me:$LINENO: $ac_try_echo\"") >&5
+  (eval "$ac_compile") 2>conftest.er1
+  ac_status=$?
+  grep -v '^ *+' conftest.er1 >conftest.err
+  rm -f conftest.er1
+  cat conftest.err >&5
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } && {
+	 test -z "$ac_c_werror_flag" ||
+	 test ! -s conftest.err
+       } && test -s conftest.$ac_objext; then
+  ac_header_compiler=yes
+else
+  echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
+	ac_header_compiler=no
+fi
+
+rm -f core conftest.err conftest.$ac_objext conftest.$ac_ext
+{ echo "$as_me:$LINENO: result: $ac_header_compiler" >&5
+echo "${ECHO_T}$ac_header_compiler" >&6; }
+
+# Is the header present?
+{ echo "$as_me:$LINENO: checking magick/MagickCore.h presence" >&5
+echo $ECHO_N "checking magick/MagickCore.h presence... $ECHO_C" >&6; }
+cat >conftest.$ac_ext <<_ACEOF
+/* confdefs.h.  */
+_ACEOF
+cat confdefs.h >>conftest.$ac_ext
+cat >>conftest.$ac_ext <<_ACEOF
+/* end confdefs.h.  */
+#include <magick/MagickCore.h>
+_ACEOF
+if { (ac_try="$ac_cpp conftest.$ac_ext"
+case "(($ac_try" in
+  *\"* | *\`* | *\\*) ac_try_echo=\$ac_try;;
+  *) ac_try_echo=$ac_try;;
+esac
+eval "echo \"\$as_me:$LINENO: $ac_try_echo\"") >&5
+  (eval "$ac_cpp conftest.$ac_ext") 2>conftest.er1
+  ac_status=$?
+  grep -v '^ *+' conftest.er1 >conftest.err
+  rm -f conftest.er1
+  cat conftest.err >&5
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } >/dev/null && {
+	 test -z "$ac_c_preproc_warn_flag$ac_c_werror_flag" ||
+	 test ! -s conftest.err
+       }; then
+  ac_header_preproc=yes
+else
+  echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
+  ac_header_preproc=no
+fi
+
+rm -f conftest.err conftest.$ac_ext
+{ echo "$as_me:$LINENO: result: $ac_header_preproc" >&5
+echo "${ECHO_T}$ac_header_preproc" >&6; }
+
+# So?  What about this header?
+case $ac_header_compiler:$ac_header_preproc:$ac_c_preproc_warn_flag in
+  yes:no: )
+    { echo "$as_me:$LINENO: WARNING: magick/MagickCore.h: accepted by the compiler, rejected by the preprocessor!" >&5
+echo "$as_me: WARNING: magick/MagickCore.h: accepted by the compiler, rejected by the preprocessor!" >&2;}
+    { echo "$as_me:$LINENO: WARNING: magick/MagickCore.h: proceeding with the compiler's result" >&5
+echo "$as_me: WARNING: magick/MagickCore.h: proceeding with the compiler's result" >&2;}
+    ac_header_preproc=yes
+    ;;
+  no:yes:* )
+    { echo "$as_me:$LINENO: WARNING: magick/MagickCore.h: present but cannot be compiled" >&5
+echo "$as_me: WARNING: magick/MagickCore.h: present but cannot be compiled" >&2;}
+    { echo "$as_me:$LINENO: WARNING: magick/MagickCore.h:     check for missing prerequisite headers?" >&5
+echo "$as_me: WARNING: magick/MagickCore.h:     check for missing prerequisite headers?" >&2;}
+    { echo "$as_me:$LINENO: WARNING: magick/MagickCore.h: see the Autoconf documentation" >&5
+echo "$as_me: WARNING: magick/MagickCore.h: see the Autoconf documentation" >&2;}
+    { echo "$as_me:$LINENO: WARNING: magick/MagickCore.h:     section \"Present But Cannot Be Compiled\"" >&5
+echo "$as_me: WARNING: magick/MagickCore.h:     section \"Present But Cannot Be Compiled\"" >&2;}
+    { echo "$as_me:$LINENO: WARNING: magick/MagickCore.h: proceeding with the preprocessor's result" >&5
+echo "$as_me: WARNING: magick/MagickCore.h: proceeding with the preprocessor's result" >&2;}
+    { echo "$as_me:$LINENO: WARNING: magick/MagickCore.h: in the future, the compiler will take precedence" >&5
+echo "$as_me: WARNING: magick/MagickCore.h: in the future, the compiler will take precedence" >&2;}
+    ( cat <<\_ASBOX
+## ----------------------------- ##
+## Report this to libdodo.sf.net ##
+## ----------------------------- ##
+_ASBOX
+     ) | sed "s/^/$as_me: WARNING:     /" >&2
+    ;;
+esac
+{ echo "$as_me:$LINENO: checking for magick/MagickCore.h" >&5
+echo $ECHO_N "checking for magick/MagickCore.h... $ECHO_C" >&6; }
+if test "${ac_cv_header_magick_MagickCore_h+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+  ac_cv_header_magick_MagickCore_h=$ac_header_preproc
+fi
+{ echo "$as_me:$LINENO: result: $ac_cv_header_magick_MagickCore_h" >&5
+echo "${ECHO_T}$ac_cv_header_magick_MagickCore_h" >&6; }
+
+fi
+
+
+		echo -n -e "#define IMAGEMAGICK_EXT\n\n" >> include/libdodo/directives.runtime.h
+
+		RESULT="$RESULT\nIMAGEMAGICK\t\t\t\t\t\tenabled"
+	else
+		RESULT="$RESULT\nIMAGEMAGICK\t\t\t\t\t\tdisabled"
 	fi
 
 # Checks for header files.
