systemLibraryLoader started

diff --git a/trunk/configure b/trunk/configure
--- a/trunk/configure
+++ b/trunk/configure
@@ -1282,6 +1282,7 @@ Optional Packages:
   --with-PACKAGE[=ARG]    use PACKAGE [ARG=yes]
   --without-PACKAGE       do not use PACKAGE (same as --with-PACKAGE=no)
   --with-sqlite3(=/path)  use sqlite3
+  --with-bfd(=/path)      support library name resolution
   --with-postgresql(=/path)
                           use postgresql
   --with-mysql(=/path)    use mysql
@@ -4321,6 +4322,243 @@ fi
 		RESULT="$RESULT\nSQLite\t\t\t\t\t\tenabled"
 	else
 		RESULT="$RESULT\nSQLite\t\t\t\t\t\tdisabled"
+	fi
+
+
+# Check whether --with-bfd was given.
+if test "${with_bfd+set}" = set; then
+  withval=$with_bfd; MOD_BFD_DIR="$withval"
+else
+  MOD_BFD="no"
+fi
+
+	if test "$MOD_BFD" != "no"
+	then
+		if test "$MOD_BFD_DIR" = "yes"
+		then
+			MOD_BFD_DIR=/usr
+		fi
+		CPPFLAGS="$CPPFLAGS -I$MOD_BFD_DIR/include"
+		LDFLAGS="$LDFLAGS -L$MOD_BFD_DIR/lib -lbfd"
+
+{ echo "$as_me:$LINENO: checking for bfd_fopen in -lbfd" >&5
+echo $ECHO_N "checking for bfd_fopen in -lbfd... $ECHO_C" >&6; }
+if test "${ac_cv_lib_bfd_bfd_fopen+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+  ac_check_lib_save_LIBS=$LIBS
+LIBS="-lbfd  $LIBS"
+cat >conftest.$ac_ext <<_ACEOF
+/* confdefs.h.  */
+_ACEOF
+cat confdefs.h >>conftest.$ac_ext
+cat >>conftest.$ac_ext <<_ACEOF
+/* end confdefs.h.  */
+
+/* Override any GCC internal prototype to avoid an error.
+   Use char because int might match the return type of a GCC
+   builtin and then its argument prototype would still apply.  */
+#ifdef __cplusplus
+extern "C"
+#endif
+char bfd_fopen ();
+int
+main ()
+{
+return bfd_fopen ();
+  ;
+  return 0;
+}
+_ACEOF
+rm -f conftest.$ac_objext conftest$ac_exeext
+if { (ac_try="$ac_link"
+case "(($ac_try" in
+  *\"* | *\`* | *\\*) ac_try_echo=\$ac_try;;
+  *) ac_try_echo=$ac_try;;
+esac
+eval "echo \"\$as_me:$LINENO: $ac_try_echo\"") >&5
+  (eval "$ac_link") 2>conftest.er1
+  ac_status=$?
+  grep -v '^ *+' conftest.er1 >conftest.err
+  rm -f conftest.er1
+  cat conftest.err >&5
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } && {
+	 test -z "$ac_c_werror_flag" ||
+	 test ! -s conftest.err
+       } && test -s conftest$ac_exeext &&
+       $as_test_x conftest$ac_exeext; then
+  ac_cv_lib_bfd_bfd_fopen=yes
+else
+  echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
+	ac_cv_lib_bfd_bfd_fopen=no
+fi
+
+rm -f core conftest.err conftest.$ac_objext conftest_ipa8_conftest.oo \
+      conftest$ac_exeext conftest.$ac_ext
+LIBS=$ac_check_lib_save_LIBS
+fi
+{ echo "$as_me:$LINENO: result: $ac_cv_lib_bfd_bfd_fopen" >&5
+echo "${ECHO_T}$ac_cv_lib_bfd_bfd_fopen" >&6; }
+if test $ac_cv_lib_bfd_bfd_fopen = yes; then
+  cat >>confdefs.h <<_ACEOF
+#define HAVE_LIBBFD 1
+_ACEOF
+
+  LIBS="-lbfd $LIBS"
+
+else
+  { { echo "$as_me:$LINENO: error: bfd lib was not found" >&5
+echo "$as_me: error: bfd lib was not found" >&2;}
+   { (exit 1); exit 1; }; }
+fi
+
+		if test "${ac_cv_header_bfd_h+set}" = set; then
+  { echo "$as_me:$LINENO: checking for bfd.h" >&5
+echo $ECHO_N "checking for bfd.h... $ECHO_C" >&6; }
+if test "${ac_cv_header_bfd_h+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+fi
+{ echo "$as_me:$LINENO: result: $ac_cv_header_bfd_h" >&5
+echo "${ECHO_T}$ac_cv_header_bfd_h" >&6; }
+else
+  # Is the header compilable?
+{ echo "$as_me:$LINENO: checking bfd.h usability" >&5
+echo $ECHO_N "checking bfd.h usability... $ECHO_C" >&6; }
+cat >conftest.$ac_ext <<_ACEOF
+/* confdefs.h.  */
+_ACEOF
+cat confdefs.h >>conftest.$ac_ext
+cat >>conftest.$ac_ext <<_ACEOF
+/* end confdefs.h.  */
+$ac_includes_default
+#include <bfd.h>
+_ACEOF
+rm -f conftest.$ac_objext
+if { (ac_try="$ac_compile"
+case "(($ac_try" in
+  *\"* | *\`* | *\\*) ac_try_echo=\$ac_try;;
+  *) ac_try_echo=$ac_try;;
+esac
+eval "echo \"\$as_me:$LINENO: $ac_try_echo\"") >&5
+  (eval "$ac_compile") 2>conftest.er1
+  ac_status=$?
+  grep -v '^ *+' conftest.er1 >conftest.err
+  rm -f conftest.er1
+  cat conftest.err >&5
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } && {
+	 test -z "$ac_c_werror_flag" ||
+	 test ! -s conftest.err
+       } && test -s conftest.$ac_objext; then
+  ac_header_compiler=yes
+else
+  echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
+	ac_header_compiler=no
+fi
+
+rm -f core conftest.err conftest.$ac_objext conftest.$ac_ext
+{ echo "$as_me:$LINENO: result: $ac_header_compiler" >&5
+echo "${ECHO_T}$ac_header_compiler" >&6; }
+
+# Is the header present?
+{ echo "$as_me:$LINENO: checking bfd.h presence" >&5
+echo $ECHO_N "checking bfd.h presence... $ECHO_C" >&6; }
+cat >conftest.$ac_ext <<_ACEOF
+/* confdefs.h.  */
+_ACEOF
+cat confdefs.h >>conftest.$ac_ext
+cat >>conftest.$ac_ext <<_ACEOF
+/* end confdefs.h.  */
+#include <bfd.h>
+_ACEOF
+if { (ac_try="$ac_cpp conftest.$ac_ext"
+case "(($ac_try" in
+  *\"* | *\`* | *\\*) ac_try_echo=\$ac_try;;
+  *) ac_try_echo=$ac_try;;
+esac
+eval "echo \"\$as_me:$LINENO: $ac_try_echo\"") >&5
+  (eval "$ac_cpp conftest.$ac_ext") 2>conftest.er1
+  ac_status=$?
+  grep -v '^ *+' conftest.er1 >conftest.err
+  rm -f conftest.er1
+  cat conftest.err >&5
+  echo "$as_me:$LINENO: \$? = $ac_status" >&5
+  (exit $ac_status); } >/dev/null && {
+	 test -z "$ac_c_preproc_warn_flag$ac_c_werror_flag" ||
+	 test ! -s conftest.err
+       }; then
+  ac_header_preproc=yes
+else
+  echo "$as_me: failed program was:" >&5
+sed 's/^/| /' conftest.$ac_ext >&5
+
+  ac_header_preproc=no
+fi
+
+rm -f conftest.err conftest.$ac_ext
+{ echo "$as_me:$LINENO: result: $ac_header_preproc" >&5
+echo "${ECHO_T}$ac_header_preproc" >&6; }
+
+# So?  What about this header?
+case $ac_header_compiler:$ac_header_preproc:$ac_c_preproc_warn_flag in
+  yes:no: )
+    { echo "$as_me:$LINENO: WARNING: bfd.h: accepted by the compiler, rejected by the preprocessor!" >&5
+echo "$as_me: WARNING: bfd.h: accepted by the compiler, rejected by the preprocessor!" >&2;}
+    { echo "$as_me:$LINENO: WARNING: bfd.h: proceeding with the compiler's result" >&5
+echo "$as_me: WARNING: bfd.h: proceeding with the compiler's result" >&2;}
+    ac_header_preproc=yes
+    ;;
+  no:yes:* )
+    { echo "$as_me:$LINENO: WARNING: bfd.h: present but cannot be compiled" >&5
+echo "$as_me: WARNING: bfd.h: present but cannot be compiled" >&2;}
+    { echo "$as_me:$LINENO: WARNING: bfd.h:     check for missing prerequisite headers?" >&5
+echo "$as_me: WARNING: bfd.h:     check for missing prerequisite headers?" >&2;}
+    { echo "$as_me:$LINENO: WARNING: bfd.h: see the Autoconf documentation" >&5
+echo "$as_me: WARNING: bfd.h: see the Autoconf documentation" >&2;}
+    { echo "$as_me:$LINENO: WARNING: bfd.h:     section \"Present But Cannot Be Compiled\"" >&5
+echo "$as_me: WARNING: bfd.h:     section \"Present But Cannot Be Compiled\"" >&2;}
+    { echo "$as_me:$LINENO: WARNING: bfd.h: proceeding with the preprocessor's result" >&5
+echo "$as_me: WARNING: bfd.h: proceeding with the preprocessor's result" >&2;}
+    { echo "$as_me:$LINENO: WARNING: bfd.h: in the future, the compiler will take precedence" >&5
+echo "$as_me: WARNING: bfd.h: in the future, the compiler will take precedence" >&2;}
+    ( cat <<\_ASBOX
+## ----------------------------- ##
+## Report this to libdodo.sf.net ##
+## ----------------------------- ##
+_ASBOX
+     ) | sed "s/^/$as_me: WARNING:     /" >&2
+    ;;
+esac
+{ echo "$as_me:$LINENO: checking for bfd.h" >&5
+echo $ECHO_N "checking for bfd.h... $ECHO_C" >&6; }
+if test "${ac_cv_header_bfd_h+set}" = set; then
+  echo $ECHO_N "(cached) $ECHO_C" >&6
+else
+  ac_cv_header_bfd_h=$ac_header_preproc
+fi
+{ echo "$as_me:$LINENO: result: $ac_cv_header_bfd_h" >&5
+echo "${ECHO_T}$ac_cv_header_bfd_h" >&6; }
+
+fi
+if test $ac_cv_header_bfd_h = yes; then
+  :
+else
+  { { echo "$as_me:$LINENO: error: bfd header was not found" >&5
+echo "$as_me: error: bfd header was not found" >&2;}
+   { (exit 1); exit 1; }; }
+fi
+
+
+		echo -n -e "#define BFD_EXT\n\n" >> include/libdodo/directives.runtime.h
+
+		RESULT="$RESULT\nLibrary name resolution\t\t\t\t\t\tenabled"
+	else
+		RESULT="$RESULT\nLibrary name resolution\t\t\t\t\t\tdisabled"
 	fi
 
 
